name: Linux on push
on:
    push:
        paths:
            -   'src/**'
            -   'Makefile'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Install dependencies
                run: sudo apt-get update && sudo apt-get install -y libtss2-dev nlohmann-json3-dev

            -   name: Build
                run: make